fun main(){
    print("student enrollment number :")
    var en= readLine()
    print("student name :")
    var name = readLine()
    print("student Branch :")
    var branch= readLine()
    print("student class : ")
    var cl= readLine()
    print("student batch : ")
    var batch= readLine()
    print("student college name : ")
    var college= readLine()
    print("student university name : ")
    var uni= readLine()
    print("student age : ")
    var age= readLine()
    println()
    println("student data: ")
    println("student enrollment number : $en")
    println("student name is : $name")
    println("student Branch is : $branch")
    println("student class is : $cl")
    println("student batch is: $batch")
    println("student college name is :$college")
    println("student university name is : $uni")
    println("studet age is : $age")

}